In [1]:
import pandas as pd

In [2]:
resultados_dos_processos = 'data/Hackaton_Enter_Base_Candidatos_Resultados_dos_processos.csv'
df_resultados_dos_processos = pd.read_csv(resultados_dos_processos)
subsidios_disponibilizados = 'data/Hackaton_Enter_Base_Candidatos_Subsídios_disponibilizados.csv'
df_subsidios_disponibilizados = pd.read_csv(subsidios_disponibilizados, header = 1)

In [3]:
df_resultados_dos_processos.head()

,Número do processo,UF,Assunto,Sub-assunto,Resultado macro,Resultado micro,Valor da causa,Valor da condenação/indenização
0,1764352-89.2025.8.06.1818,CE,Não reconhece operação,Genérico,Não Êxito,Parcial procedência,"13.534,00","7.714,38"
1,5638325-36.2025.8.17.4124,PE,Não reconhece operação,Golpe,Não Êxito,Parcial procedência,"7.883,63","3.784,14"
2,1037491-89.2025.8.18.1658,PI,Não reconhece operação,Golpe,Não Êxito,Parcial procedência,"8.561,97","6.507,10"
3,9547931-23.2025.8.04.4188,AM,Não reconhece operação,Golpe,Êxito,Improcedência,"5.693,13","0,00"
4,9999446-69.2025.8.04.4264,AM,Não reconhece operação,Golpe,Êxito,Improcedência,"8.515,67","0,00"

In [4]:
df_subsidios_disponibilizados.head()

,Número do processo,Contrato,Extrato,Comprovante de crédito,Dossiê,Demonstrativo de evolução da dívida,Laudo referenciado
0,1764352-89.2025.8.06.1818,0,0,0,1,1,1
1,5638325-36.2025.8.17.4124,1,1,0,1,1,1
2,1037491-89.2025.8.18.1658,0,1,1,1,1,0
3,9547931-23.2025.8.04.4188,1,1,1,1,1,0
4,9999446-69.2025.8.04.4264,0,1,0,1,1,1

In [17]:
#Unificação do Banco de Dados
df_unificado = df_resultados_dos_processos.merge(
    df_subsidios_disponibilizados,
    on='Número do processo',
    how='left'  # ou 'inner', dependendo do caso
)

In [18]:
df_unificado.head()

,Número do processo,UF,Assunto,Sub-assunto,Resultado macro,Resultado micro,Valor da causa,Valor da condenação/indenização,Contrato,Extrato,Comprovante de crédito,Dossiê,Demonstrativo de evolução da dívida,Laudo referenciado
0,1764352-89.2025.8.06.1818,CE,Não reconhece operação,Genérico,Não Êxito,Parcial procedência,"13.534,00","7.714,38",0,0,0,1,1,1
1,5638325-36.2025.8.17.4124,PE,Não reconhece operação,Golpe,Não Êxito,Parcial procedência,"7.883,63","3.784,14",1,1,0,1,1,1
2,1037491-89.2025.8.18.1658,PI,Não reconhece operação,Golpe,Não Êxito,Parcial procedência,"8.561,97","6.507,10",0,1,1,1,1,0
3,9547931-23.2025.8.04.4188,AM,Não reconhece operação,Golpe,Êxito,Improcedência,"5.693,13","0,00",1,1,1,1,1,0
4,9999446-69.2025.8.04.4264,AM,Não reconhece operação,Golpe,Êxito,Improcedência,"8.515,67","0,00",0,1,0,1,1,1

In [19]:
df_unificado["Resultado macro"]  = df_unificado["Resultado macro"].map({"Não Êxito": 0, "Êxito": 1})
df_unificado

,Número do processo,UF,Assunto,Sub-assunto,Resultado macro,Resultado micro,Valor da causa,Valor da condenação/indenização,Contrato,Extrato,Comprovante de crédito,Dossiê,Demonstrativo de evolução da dívida,Laudo referenciado
0,1764352-89.2025.8.06.1818,CE,Não reconhece operação,Genérico,0,Parcial procedência,"13.534,00","7.714,38",0,0,0,1,1,1
1,5638325-36.2025.8.17.4124,PE,Não reconhece operação,Golpe,0,Parcial procedência,"7.883,63","3.784,14",1,1,0,1,1,1
2,1037491-89.2025.8.18.1658,PI,Não reconhece operação,Golpe,0,Parcial procedência,"8.561,97","6.507,10",0,1,1,1,1,0
3,9547931-23.2025.8.04.4188,AM,Não reconhece operação,Golpe,1,Improcedência,"5.693,13","0,00",1,1,1,1,1,0
4,9999446-69.2025.8.04.4264,AM,Não reconhece operação,Golpe,1,Improcedência,"8.515,67","0,00",0,1,0,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59995,5948422-40.2025.8.25.9205,SE,Não reconhece operação,Genérico,1,Extinção,"11.777,37","0,00",1,1,0,1,1,1
59996,7271337-72.2025.8.17.3193,PE,Não reconhece operação,Golpe,1,Extinção,"16.575,93","0,00",1,1,1,0,0,1
59997,8668390-32.2025.8.01.9603,AC,Não reconhece operação,Genérico,0,Parcial procedência,"20.517,82","14.157,30",0,1,0,1,1,1
59998,8052515-88.2025.8.07.3354,DF,Não reconhece operação,Genérico,1,Improcedência,"14.069,63","0,00",1,1,1,0,0,1
59999,6936655-34.2025.8.26.1473,SP,Não reconhece operação,Golpe,1,Improcedência,"14.771,05","0,00",1,1,1,1,1,1

In [ ]:
df_unificado.head()

,Número do processo,UF,Assunto,Sub-assunto,Resultado macro,Resultado micro,Valor da causa,Valor da condenação/indenização,Contrato,Extrato,Comprovante de crédito,Dossiê,Demonstrativo de evolução da dívida,Laudo referenciado
0,1764352-89.2025.8.06.1818,CE,Não reconhece operação,Genérico,0,Parcial procedência,"13.534,00","7.714,38",0,0,0,1,1,1
1,5638325-36.2025.8.17.4124,PE,Não reconhece operação,Golpe,0,Parcial procedência,"7.883,63","3.784,14",1,1,0,1,1,1
2,1037491-89.2025.8.18.1658,PI,Não reconhece operação,Golpe,0,Parcial procedência,"8.561,97","6.507,10",0,1,1,1,1,0
3,9547931-23.2025.8.04.4188,AM,Não reconhece operação,Golpe,1,Improcedência,"5.693,13","0,00",1,1,1,1,1,0
4,9999446-69.2025.8.04.4264,AM,Não reconhece operação,Golpe,1,Improcedência,"8.515,67","0,00",0,1,0,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59995,5948422-40.2025.8.25.9205,SE,Não reconhece operação,Genérico,1,Extinção,"11.777,37","0,00",1,1,0,1,1,1
59996,7271337-72.2025.8.17.3193,PE,Não reconhece operação,Golpe,1,Extinção,"16.575,93","0,00",1,1,1,0,0,1
59997,8668390-32.2025.8.01.9603,AC,Não reconhece operação,Genérico,0,Parcial procedência,"20.517,82","14.157,30",0,1,0,1,1,1
59998,8052515-88.2025.8.07.3354,DF,Não reconhece operação,Genérico,1,Improcedência,"14.069,63","0,00",1,1,1,0,0,1
59999,6936655-34.2025.8.26.1473,SP,Não reconhece operação,Golpe,1,Improcedência,"14.771,05","0,00",1,1,1,1,1,1

In [21]:
df_unificado.to_csv('data/Hackaton_Enter_Banco_unificado.csv', index=False)